# Generated by Django 5.2.7 on 2025-10-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wrong_code_actions',
            field=models.IntegerField(default=0),
        ),
    ]
