# Generated by Django 5.2.7 on 2025-10-30 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('repeat_status', models.CharField(choices=[('none', 'Нет'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('yearly', 'Каждый год')])),
                ('end_repeat', models.CharField(choices=[('never', 'Никогда'), ('date', 'По дате')])),
                ('end_repeat_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('alert', models.CharField(choices=[('none', 'Нет'), ('30m', 'За 30 минут'), ('1h', 'За 1 час'), ('2h', 'За 2 часа'), ('3h', 'За 3 часа'), ('1d', 'В начале дня')])),
                ('next_time', models.DateTimeField(blank=True, null=True)),
                ('next_alert_time', models.DateTimeField(blank=True, null=True)),
                ('active_alert', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
